### PR TITLE
Contact page update

### PR DESCRIPTION
**Pull request by evagolabek**
short description: 'contact page' changed to 'orders page' plus few changes of how the orders are displayed

### CODE REVIEW

**Comment by Ju1111** [comment]
Are you overwriting the contact page file here? because we'd need that one as well for internal users

**Comment by Safisyx** [comment]
I asked her to change the name, since it was only showing orders list anyway 😃 
If we want to have an overview of all contacts then we need to create a new component

**Comment by evagolabek** [comment]
@Ruhtarduhd yes sure we can change it to email

**Comment by Ju1111** [comment]
ohhhh, I thought we had a design of a page displaying contacts haha oops. well then if that was orders all the time anyway it makes sense

**Pull request merged**
